MedTech/MedTech/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('MedTechUser.urls', namespace='MedTechUser'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MedTech/MedTechUser/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'MedTechUser'

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'send-message/$', views.sendMessage, name="send-message"),
    url(r'home2/$', views.home2, name="home2"),
    url(r'insert_data/$', views.insertData, name="insert_data" ),
    url(r'query_feeling', views.query_feeling, name="query_feeling")
]

MedTech/MedTechUser/models.py
from django.db import models

# Create your models here.


class AllFeelings(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)
    # permuterm = models.CharField(max_length=50, null=True, blank=True)
    disease = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return str(self.name) + " -- " + str(self.disease)


class AllBodyParts(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)
    permuterm = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.permuterm) + ' -- ' + str(self.name)


class SymptomsToDisease(models.Model):
    symptom = models.CharField(max_length=200, null=True, blank=True)
    body_part = models.CharField(max_length=50, null=True, blank=True)
    disease = models.CharField(max_length=100, null=True, blank=True)

class TempSymptomsToDisease(models.Model):
    symptom = models.CharField(max_length=200, null=True, blank=True)
    body_part = models.CharField(max_length=50, null=True, blank=True)
    disease = models.CharField(max_length=100, null=True, blank=True)

class TempxAllFeelings(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)
    # permuterm = models.CharField(max_length=50, null=True, blank=True)
    disease = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return str(self.name) + " -- " + str(self.disease)

class AskingSymptoms(models.Model):
    disease = models.CharField(max_length=100, null=True, blank=True)
    symptom = models.CharField(max_length=100, null=True, blank=True)

class TopDiseases(models.Model):
    disease = models.CharField(max_length=100, null=True, blank=True)

class Specialist(models.Model):
    disease = models.CharField(max_length=100, null=True, blank=True)
    doctor = models.CharField(max_length=100, null=True, blank=True)
    

MedTech/MedTechUser/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from nltk.stem.lancaster  import LancasterStemmer
# import codecs
import csv
from . models import *
import stringdist
from django.db.models import Q
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import random

count = 0

def home(request):
    global count
    TempSymptomsToDisease.objects.all().delete()
    TempxAllFeelings.objects.all().delete()
    TopDiseases.objects.all().delete()
    return render(request, 'MedTechUser/home.html', {'count':0})
    # if request.is_ajax():

def home2(request):
    global count
    TempSymptomsToDisease.objects.all().delete()
    TempxAllFeelings.objects.all().delete()
    TopDiseases.objects.all().delete()
    return render(request, 'MedTechUser/index3.html', {'count':0})


def analyze_and_reply(message):
    if message is not None:
        print(message)
        reply = 'REPLY THIS'
        return reply

def most_common(lst):
    return max(set(lst), key=lst.count)

def sendMessage(request):
    context = ''
    import itertools
    import operator

    if request.is_ajax():
        message = (request.POST.get('message', None))
        count = (request.POST.get('count', None))
        reply = ""
        print(message, count)
        if str(count) == '1':
            for part in message.split(','):
                print(part)
                global bs
                bs = SymptomsToDisease.objects.filter(Q(body_part__contains=part)|Q(body_part=part)|Q(body_part__startswith=part)|Q(body_part__endswith=part))
                for b in bs:
                    TempSymptomsToDisease(symptom = b.symptom, body_part=b.body_part, disease=b.disease).save()
            reply = "Great! I've identified the body parts - "+str(message)+". Now tell me how are you feeling in general?"
        elif count == '2':
            l = query_feeling(message)
            reply = "Let me know if you're feeling anything else like Dizziness or Nausea or Fever or Heavy.."
            # print ("l is ", l)
            for q in l:
                print (q)
                TempxAllFeelings(name = q['name'], disease = q['disease']).save()
        elif count == '3':
            try:
                x = TempSymptomsToDisease.objects.all()
                y = TempxAllFeelings.objects.all()
                li = []
                for i in x:
                    for j in y:
                        if i.disease == j.disease:
                            li.append(i.disease)
                print (li)
                top=[]
                most = most_common(li)
                top.append(most)

                li = [x for x in li if x != most]
                most = most_common(li)
                top.append(most)

                li = [x for x in li if x != most]
                most = most_common(li)
                top.append(most)
                
                print(top)

                for t in top:
                    TopDiseases(disease = t).save()

                tsd = TempSymptomsToDisease.objects.filter(disease = top[0])[0]
                reply = "Are you having "+ str(tsd.symptom)
            except:
                reply = "I'm sorry I dont seem to know your diseaese"
    
        elif count == '4':
            print("here")
            from textblob import TextBlob
            text = message
            blob = TextBlob(text)
            td = TopDiseases.objects.all()
            for sentence in blob.sentences:
                print(sentence.sentiment.polarity)
            print (message)
            if message.strip(' ')=="yes":
                print(len(td))
                print(td.last().disease)
                reply = str("you have") + str(td.last().disease)
                sp = Specialist.objects.filter(disease=td.last().disease)[0]
                if(sp):
                    reply += ". You must contact a " + sp.doctor
                    import webbrowser
                    webbrowser.open('https://www.google.co.in/search?q='+sp.doctor+'+near+me')
                    # print (reply)
                td.last().delete()
            else:
                tsd = TempSymptomsToDisease.objects.filter(disease = td.last().disease)[0]
                td.last().delete()
                reply = "Ok Do you have " + tsd.symptom
        
        elif count == '5':
            print("here")
            from textblob import TextBlob
            text = message
            blob = TextBlob(text)
            td = TopDiseases.objects.all()
            for sentence in blob.sentences:
                print(sentence.sentiment.polarity)
            if message.strip(' ')=="yes":
                print(len(td))
                print(td.last().disease)
                reply = str("you have") + str(td.last().disease)
                if(sp):
                    reply += ". You must contact a " + sp.doctor
                    import webbrowser
                    webbrowser.open('https://www.google.co.in/search?q='+sp.doctor+'+near+me')
                td.last().delete()
            else:
                tsd = TempSymptomsToDisease.objects.filter(disease = td.last().disease)[0]
                td.last().delete()

                reply = "Ok Do you have " + tsd.symptom
        
        elif count == '6':
            print("here")
            from textblob import TextBlob
            text = message
            blob = TextBlob(text)
            td = TopDiseases.objects.all()
            for sentence in blob.sentences:
                print(sentence.sentiment.polarity)
            if message.strip(' ')=="yes":
                print(len(td))
                print(td.last().disease)
                reply = str("you have") + str(td.last().disease)
                if(sp):
                    reply += ". You must contact a " + sp.doctor
                    import webbrowser
                    webbrowser.open('https://www.google.co.in/search?q='+sp.doctor+'+near+me')
                td.last().delete()
            else:
                reply = "I'm Sorry im not able to understand your disease. please try again"



            
                

                
        context = { 'reply': reply }
        print(context)
        res = JsonResponse(context, status=200)
        res['Access-Control-Allow-Origin']="*"
        return res
    else:
        context = { 'error': 'ERROR MESSAGE' }
        res = JsonResponse(context, status=400)
        return res

def StemData(input):
    # all_words = input.split(' ')
    word_tokens = word_tokenize(input)
    stemmed_string = ''
    # nltk.download('stopwords')
    # nltk.download('punkt')
    stopwords = nltk.corpus.stopwords.words('english')
    stopwords.extend([',','!','.','@','`','~','#', '$', '%', '^', '&', '*', '(', ')', '-','_','=','+','[','{','}',']',';',':','<','>','/','?'])

    # filtered_sentence = [w for w in word_tokens if not w in stopwords]
    st = LancasterStemmer()
    for word in word_tokens:
        stemmed_word = st.stem(word)
        if stemmed_word not in stopwords:
            stemmed_string += stemmed_word
    return stemmed_string  

def all_possible_string(feeling, original, disease):
    if len(feeling) >= 3:
        dummy = feeling[:3]
        # print(dummy)
        for i in range(3,len(feeling)):
            dummy += feeling[i]
            # print (dummy[::-1])
            feeling_model = AllFeelings()
            feeling_model.name = original
            feeling_model.permuterm = dummy[::-1]
            feeling_model.disease = disease
            feeling_model.save()
        all_possible_string(feeling[1:], original, disease)
    else:
        return

def insertData(request):
    if request.method == 'GET':
        return render(request, 'MedTechUser/home.html')
    if request.method == 'POST':
        csvfile = request.FILES.get('data_file', False)
        count = 0
        for row in csvfile:
            print (row)
            row = str(row).split(',')

            Specialist(disease = row[0][2:], doctor = row[1]).save()
            # print(row[0], row[1], row[2])
            # instance = SymptomsToDisease()
            # instance.symptom = str(row[2])
            # instance.body_part = str(row[1])
            # instance.disease = str(row[0])
            # instance.save()
        return HttpResponse("done")
        
        #     array = str(row).split('|')
        #     # print(array[0].replace("b'", ''), " ---> ", array[1].replace("\r\n'", ''))
        #     sym = str(array[1]).split(',')
        #     for i in range(0,len(sym)):
        #         if i == len(sym)-1:
        #             body_part = AllBodyParts()
        #             body_part.permuterm = str(sym[i])[:-5]
        #             # print(str(sym[i])[:-5])
        #             body_part.name = str(array[0]).replace("b'", '')
        #             body_part.save()
        #         else:
        #             body_part = AllBodyParts()
        #             body_part.permuterm = str(sym[i])
        #             # print(sym[i])
        #             body_part.name = str(array[0]).replace("b'", '')
        #             body_part.save()
        # return HttpResponse("success")
            # row = str(row)[2:-3].split('|')
            # feeling_model = AllFeelings()
            # feeling_model.name = str(row[1])
            # feeling_model.disease = str(row[0])
            # feeling_model.save()
            # print(count)
            # # stemmed = StemData(str(row[1]))
            # # # print(stemmed, stemmed[-1:])
            # # all_possible_string(stemmed[::-1], str(row[1]), str(row[0]))
        #     count += 1
        # return HttpResponse("success")

def all_string(symptom, final_results):
    # print(final_results)
    if len(symptom) >= 3:
        dummy = symptom[:3]
        results = AllFeelings.objects.filter(Q(name__contains=dummy[::-1])|Q(name=dummy[::-1])|Q(name__startswith=dummy[::-1])|Q(name__endswith=dummy[::-1]))

MedTech/MedTechUser/templates/MedTechUser/index.html
<!DOCTYPE html>
<html lang="en" >

<head>
  {% load staticfiles %}
  <meta charset="UTF-8">
  <title>Chat Widget</title>
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>

      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body>

    <div class="container clearfix">
    <div class="people-list" id="people-list">
      <div class="search">
        <input type="text" placeholder="search" />
        <i class="fa fa-search"></i>
      </div>
      <ul class="list">
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_01.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Vincent Porter</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_02.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Aiden Chavez</div>
            <div class="status">
              <i class="fa fa-circle offline"></i> left 7 mins ago
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_03.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Mike Thomas</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_04.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Erica Hughes</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_05.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Ginger Johnston</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_06.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Tracy Carpenter</div>
            <div class="status">
              <i class="fa fa-circle offline"></i> left 30 mins ago
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_07.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Christian Kelly</div>
            <div class="status">
              <i class="fa fa-circle offline"></i> left 10 hours ago
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_08.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Monica Ward</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_09.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Dean Henry</div>
            <div class="status">
              <i class="fa fa-circle offline"></i> offline since Oct 28
            </div>
          </div>
        </li>
        
        <li class="clearfix">
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_10.jpg" alt="avatar" />
          <div class="about">
            <div class="name">Peyton Mckinney</div>
            <div class="status">
              <i class="fa fa-circle online"></i> online
            </div>
          </div>
        </li>
      </ul>
    </div>
    
    <div class="chat">
      <div class="chat-header clearfix">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_01_green.jpg" alt="avatar" />
        
        <div class="chat-about">
          <div class="chat-with">Chat with Vincent Porter</div>
          <div class="chat-num-messages">already 1 902 messages</div>
        </div>
        <i class="fa fa-star"></i>
      </div> <!-- end chat-header -->
      
      <div class="chat-history">
        <ul>
          <li class="clearfix">
            <div class="message-data align-right">
              <span class="message-data-time" >10:10 AM, Today</span> &nbsp; &nbsp;
              <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>
              
            </div>
            <div class="message other-message float-right">
              Hi Vincent, how are you? How is the project coming along?
            </div>
          </li>
          
          <li>
            <div class="message-data">
              <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
              <span class="message-data-time">10:12 AM, Today</span>
            </div>
            <div class="message my-message">
              Are we meeting today? Project has been already finished and I have results to show you.
            </div>
          </li>
          
          <li class="clearfix">
            <div class="message-data align-right">
              <span class="message-data-time" >10:14 AM, Today</span> &nbsp; &nbsp;
              <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>
              
            </div>
            <div class="message other-message float-right">
              Well I am not sure. The rest of the team is not here yet. Maybe in an hour or so? Have you faced any problems at the last phase of the project?
            </div>
          </li>
          
          <li>
            <div class="message-data">
              <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
              <span class="message-data-time">10:20 AM, Today</span>
            </div>
            <div class="message my-message">
              Actually everything was fine. I'm very excited to show this to our team.
            </div>
          </li>
          
          <li>
            <div class="message-data">
              <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
              <span class="message-data-time">10:31 AM, Today</span>
            </div>
            <i class="fa fa-circle online"></i>
            <i class="fa fa-circle online" style="color: #AED2A6"></i>
            <i class="fa fa-circle online" style="color:#DAE9DA"></i>
          </li>
          
        </ul>
        
      </div> <!-- end chat-history -->
      
      <div class="chat-message clearfix">
        <textarea name="message-to-send" id="message-to-send" placeholder ="Type your message" rows="3"></textarea>
                
        <i class="fa fa-file-o"></i> &nbsp;&nbsp;&nbsp;
        <i class="fa fa-file-image-o"></i>
        
        <button>Send</button>

      </div> <!-- end chat-message -->
      
    </div> <!-- end chat -->
    
  </div> <!-- end container -->

<script id="message-template" type="text/x-handlebars-template">
  <li class="clearfix">
    <div class="message-data align-right">
      <span class="message-data-time" >{{time}}, Today</span> &nbsp; &nbsp;
      <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>
    </div>
    <div class="message other-message float-right">
      {{messageOutput}}
    </div>
  </li>
</script>

<script id="message-response-template" type="text/x-handlebars-template">
  <li>
    <div class="message-data">
      <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
      <span class="message-data-time">{{time}}, Today</span>
    </div>
    <div class="message my-message">
      {{response}}
    </div>
  </li>
</script>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js'></script>

  

    <script  src="{% static 'js/index.js' %}"></script>




</body>

</html>

MedTech/MedTechUser/templates/MedTechUser/index2.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Interactive Chat Box</title>
  
  
  
      <link rel="stylesheet" href="css/style.css">

  
</head>

<body>

  <div class='progress'>Work in progress</div>
<div id="viewport"></div>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>

  

    <script  src="js/index.js"></script>




</body>

</html>

MedTech/MedTechUser/templates/MedTechUser/index3.html
<html>
  {% load staticfiles %}
    <head>
        <title>MedTech</title>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.3.min.js" ></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type="text/javascript">
          var ar = [];
          function FindPosition(oElement)
          {
            if(typeof( oElement.offsetParent ) != "undefined")
            {
              for(var posX = 0, posY = 0; oElement; oElement = oElement.offsetParent)
              {
                posX += oElement.offsetLeft;
                posY += oElement.offsetTop;
              }
                return [ posX, posY ];
              }
              else
              {
                return [ oElement.x, oElement.y ];
              }
          }
          function GetCoordinatesFront(e)
          {
            var PosX = 0;
            var PosY = 0;
            var ImgPos;
            ImgPos = FindPosition(body_front);
            if (!e) var e = window.event;
            if (e.pageX || e.pageY)
            {
              PosX = e.pageX;
              PosY = e.pageY;
            }
            else if (e.clientX || e.clientY)
              {
                PosX = e.clientX + document.body.scrollLeft
                  + document.documentElement.scrollLeft;
                PosY = e.clientY + document.body.scrollTop
                  + document.documentElement.scrollTop;
              }
            PosX = PosX - ImgPos[0];
            PosY = PosY - ImgPos[1];
          
            if((PosX>=184 && PosX<=194 && PosY>=50 && PosY<=53) || (PosX>=203 && PosX<=214 && PosY>=50 && PosY<=53)){
              ar.push("eyes")
              document.getElementById("chat-message").value =ar;

              // console.log("eyes");
            }
            else if(PosX>=174 && PosX<=222 && PosY>=26 && PosY<=44){
              ar.push("head");
              document.getElementById("chat-message").value =ar;

              console.log("head")
            }
            else if(PosX>=196 && PosX<=204 && PosY>=53 && PosY<=62){
              ar.push("nose");
              document.getElementById("chat-message").value =ar;


              console.log("nose")
            }
            else if(PosX>=155 && PosX<=241 && PosY>=163 && PosY<=225){
              ar.push("stomach");
              document.getElementById("chat-message").value =ar;


              console.log("stomach")
            }
            else if(PosX>=150 && PosX<=246 && PosY>=112 && PosY<=158){
              ar.push("chest");
              document.getElementById("chat-message").value =ar;


              console.log("chest")
            }
            else if((PosX>=158 && PosX<=191 && PosY>=361 && PosY<=399) || (PosX>=205 && PosX<=236 && PosY>=365 && PosY<=397)){
              ar.push("knees");
              document.getElementById("chat-message").value =ar;
              
              
              console.log("knees");
            }
            else if(PosX>=143 && PosX<=247 && PosY>=287 && PosY<=526){
              ar.push("legs");
              document.getElementById("chat-message").value =ar;

              console.log("legs")
            }
            else if((PosX>=27 && PosX<=72 && PosY>=242 && PosY<=284) || (PosX>=324 && PosX<=378 && PosY>=241 && PosY<=279)){
              ar.push("hands");
              
              document.getElementById("chat-message").value =ar;
              
              console.log("hands");
            }
            else if((PosX>=61 && PosX<=142 && PosY>=107 && PosY<=249) || (PosX>=248 && PosX<=346 && PosY>=108 && PosY<=232)){
              ar.push("arms");
              
              document.getElementById("chat-message").value = ar;
              
              console.log("arms")
            }  
            else if(PosX>=184 && PosX<=218 && PosY>=82 && PosY<=102){
              ar.push("neck");
              
              document.getElementById("chat-message").value = ar;
              console.log("neck")
            }
            else if(PosX>=156 && PosX<=248 && PosY>=240 && PosY<=278){
              ar.push("reproductive");
              
              document.getElementById("chat-message").value = ar;
              console.log("reproductive")
            }
            else if(PosX>=277 && PosX<=392 && PosY>=334 && PosY<=596){
              ar.push("other");
              
              document.getElementById("chat-message").value = ar;
              console.log('other')
            }
          
            
          }
          function GetCoordinatesBack(e)
          {
            var PosX = 0;
            var PosY = 0;
            var ImgPos;
            ImgPos = FindPosition(body_front);
            if (!e) var e = window.event;
            if (e.pageX || e.pageY)
            {
              PosX = e.pageX;
              PosY = e.pageY;
            }
            else if (e.clientX || e.clientY)
              {
                PosX = e.clientX + document.body.scrollLeft
                  + document.documentElement.scrollLeft;
                PosY = e.clientY + document.body.scrollTop
                  + document.documentElement.scrollTop;
              }
            PosX = PosX - ImgPos[0];
            PosY = PosY - ImgPos[1];
            if(PosX>=554 && PosX<=654 && PosY>=96 && PosY<=222){
              // console.log("back")
              ar.push("arms");
              document.getElementById("chat-message").value =ar;
            }
          }
          </script>
      </head>
    <body>
        <!-- <div id="feelings">
          <div id="chat_history">Allright then tell how are you feeling? Please mention your general body feeling.</div>
          I am Feeling <input type="text" id="chat-message" value="" name="chat_message"><br>
          <button type="button" onclick="send_message()">SUBMIT</button>
        </div> -->

        <div id="body_parts">
          <div id="">Hello Human! Do You have any pain or inconvenience in any body part?</div>
          <button id="body_yes" type="button" onclick="yesSelectBody()">Yes</button>
          <button id="body_no" type="button" onclick="noSelectBody()">No</button>
          <img id="body_front" alt="" src="{% static 'img/body_front.jpg' %}" width="400" height="600" />
          <img id="body_back" alt="" src="{% static 'img/body_back.jpg' %}" width="400" height="600" />
          
          <div id="chat_history_body"></div>
        </div>
        <b id="body_part_display"> </b>
        <input style="width:100%" type="text" id="chat-message" value="" name="chat_message"><br>
        <button type="button" onclick="send_message()">SUBMIT</button>
        <!-- <b id="back_body_part"> </b> -->

        <script type="text/javascript">
        var body_front = document.getElementById("body_front");
        var body_back = document.getElementById("body_back");
        
        body_front.onmousedown = GetCoordinatesFront;
        body_back.onmousedown = GetCoordinatesBack;
        </script>
        
        
    </body>
    <script>
        window.onload = function() {
          var link = document.getElementById('feelings');
          link.style.display = 'none';
        };

        var p1 = document.getElementById("chat-message");
        p1.addEventListener("keydown", function (e) {
            if (e.keyCode === 13) {
                send_message();
            }
        });
        
        function yesSelectBody(){
          console.log("yes")
          var chat_history = $('#chat_history_body').html();
          chat_history += "<span style='color:green'>Yes</span>" + '<br>';
          chat_history += "Select Body Parts From the image given - "
          $('#chat_history_body').html(chat_history);
          $("#body_yes").prop("disabled",true);
          $("#body_no").prop("disabled",true);
          
        }

        function noSelectBody(){
          var link = document.getElementById('feelings');
          link.style.display = '';
          document.getElementById('body_parts').style.display = 'none';
        }
        var count = 0;
        function send_message()
        {
          count += 1
            var message = $('#chat-message').val();
            console.log(message);
            $.ajax({
                url: "{% url 'MedTechUser:send-message' %}",
                type: "POST",
                dataType: 'json',
                data: { 'message': message, "count":count, "csrfmiddlewaretoken": '{{ csrf_token }}' },
                success: data => {
                  console.log("data is", data)
                    var chat_history = $('#chat_history_body').html();

                    chat_history += message + '<br>';
                    chat_history += data.reply + '<br>';

                    $('#chat_history_body').html(chat_history);

                    $('#chat-message').val(' ');
                },
                error: data => {
                    alert(data.responseJSON.error);
                }
            });
        }
    </script>
    
</html>